FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /

# Setup Conda
RUN curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -o miniforge.sh \
    && bash miniforge.sh -b -p ~/miniforge \
    && rm miniforge.sh

ENV PATH="/root/miniforge/bin:${PATH}"
RUN conda init bash \
    && echo "conda activate moose" >> /root/.bashrc

# Setup MOOSE environment
RUN conda update --all --yes \
    && conda config --add channels https://conda.software.inl.gov/public \
    && conda create -n moose moose python=3.11 -y

ENV PATH="/root/miniforge/envs/moose/bin:/root/miniforge/envs/moose/moose/bin:${PATH}"

# Install Python requirements
COPY requirements.txt .
RUN conda run -n moose pip install -r requirements.txt

# Copy necessary files
COPY ./src/utils.py ./src/monitor_system.py ./
COPY ./examples/fem_calculation/PrismsWithNamedSurfaces.inp ./examples/fem_calculation/stressed.i ./
COPY ./examples/fem_calculation_optimization/runscript.sh ./

RUN chmod +x runscript.sh

# Set up aliases and final configurations
RUN echo "alias ls='ls -al'" >> /root/.bashrc

SHELL ["conda", "run", "-n", "moose", "/bin/bash", "-c"]





